require 'rails_helper'
require 'spec_helper'
require 'shared_contexts'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dashboards", type: :request do
  include_context 'api request authentication helper methods'
  include_context 'api request global before and after hooks'
  # This should return the minimal set of attributes required to create a valid
  # Dashboard. As you add validations to Dashboard, be sure to
  # adjust the attributes here as well.
  let!(:user) { create(:user) }

  before :each do
    sign_in user
  end

  describe "GET /index" do
    it "renders a successful response" do
      3.times { FactoryBot.create(:provider, :with_bank, user: user) }
      get dashboards_url
      expect(response).to be_successful
      expect(Provider.count).to be > 2
      expect(Bank.count).to be > 2
    end
  end
end
